using NetTopologySuite.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;
using System.Text.Json;
using NetTopologySuite.IO;
using NetTopologySuite.Geometries;

namespace MapsDisplay.Features.LocalAuthority.Controllers
{
    [Route("api/tiles")]
    [ApiController]
    public class TilesController : ControllerBase
    {
        // get local_authorities.mbtiles file directory from Features/Data/Datasets folder 
        // (the file is generated by Tippecanoe [for more info look at INSTRUCTION_TO_GENERATE_MBTILES.MD])
        private readonly string mbtilesPath = Path.Combine(Directory.GetCurrentDirectory(), "Features", "LocalAuthority", "Data", "Datasets", "local_authorities.mbtiles");

        [HttpGet("{z:int}/{x:int}/{y:int}.pbf")]
        public IActionResult GetTile(int z, int x, int y)
        {
            if (!System.IO.File.Exists(mbtilesPath))
                return NotFound();

            SQLitePCL.Batteries_V2.Init();

            using var connection = new SqliteConnection($"Data Source={mbtilesPath};");
            connection.Open();

            var command = connection.CreateCommand();
            command.CommandText = "SELECT tile_data FROM tiles WHERE zoom_level = @z AND tile_column = @x AND tile_row = @y";
            command.Parameters.AddWithValue("@z", z);
            command.Parameters.AddWithValue("@x", x);
            command.Parameters.AddWithValue("@y", FlipY(z, y));  // Flip TMS to XYZ

            var tileData = command.ExecuteScalar() as byte[];

            if (tileData != null)
            {
                return new FileContentResult(tileData, "application/x-protobuf");
            }

            return NoContent();
        }

        // a look up table that saves coordinates based on the district name
        // this method generate local_authority_district.geojson file in Features/LocalAuthority/Data/Datasets folder
        [HttpGet("generate-lookup-file")]
        public void GenerateLookup()
        {
            string geoJsonPath = Path.Combine(
                Directory.GetCurrentDirectory(),
                "Features", "LocalAuthority", "Data", "Datasets", "local_authority_district.geojson"
            );

            var geoJsonText = System.IO.File.ReadAllText(geoJsonPath);
            var reader = new GeoJsonReader();
            var featureCollection = reader.Read<FeatureCollection>(geoJsonText);

            var lookup = new Dictionary<string, object>();

            foreach (var feature in featureCollection)
            {
                var name = feature.Attributes["name"].ToString();
                var geometry = feature.Geometry;
                var geometryData = new object();

                if (geometry is Point point)
                {
                    geometryData = new
                    {
                        type = "Point",
                        coordinates = new[] { point.X, point.Y }
                    };
                }
                else if (geometry is Polygon polygon)
                {
                    geometryData = new
                    {
                        type = "Polygon",
                        coordinates = new[]
                        {
                                polygon.Shell.Coordinates
                                    .Select(c => new[] { c.X, c.Y })
                                    .ToArray()
                            }
                        .Concat(
                            polygon.Holes.Select(
                                hole => hole.Coordinates
                                            .Select(c => new[] { c.X, c.Y })
                                            .ToArray()
                            )
                        ).ToArray()
                    };
                }
                else if (geometry is MultiPolygon multiPolygon)
                {
                    geometryData = new
                    {
                        type = "MultiPolygon",
                        coordinates = multiPolygon.Geometries
                            .Select(p => p.Coordinates
                                .Select(c => new[] { c.X, c.Y })
                                .ToArray())
                            .ToArray()
                    };
                }
                else
                {
                    // Handle other geometry types as needed (LineString, MultiLineString, etc.)
                    geometryData = new
                    {
                        type = geometry.GeometryType,
                        coordinates = "Unsupported geometry type"
                    };
                }

                // Add to lookup dictionary
                lookup[name] = geometryData;
            }

            var outputJson = JsonSerializer.Serialize(lookup);
            System.IO.File.WriteAllText("lookup.json", outputJson);

            Console.WriteLine("lookup.json has been created!");
        }

        private static int FlipY(int zoom, int y) => (1 << zoom) - 1 - y;
    }

}
