using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;
using System.Text.Json;

namespace MapsDisplay.Features.LocalAuthority.Controllers
{
    [Route("api/tiles")]
    [ApiController]
    public class TilesController : ControllerBase
    {
        // get local_authorities.mbtiles file directory from Features/Data/Datasets folder 
        // (the file is generated by Tippecanoe [for more info look at INSTRUCTION_TO_GENERATE_MBTILES.MD])
        private readonly string mbtilesPath = Path.Combine(Directory.GetCurrentDirectory(), "Features", "LocalAuthority", "Data", "Datasets", "local_authorities.mbtiles");

        [HttpGet("{z:int}/{x:int}/{y:int}.pbf")]
        public IActionResult GetTile(int z, int x, int y)
        {
            if (!System.IO.File.Exists(mbtilesPath))
                return NotFound();

            SQLitePCL.Batteries_V2.Init();

            using var connection = new SqliteConnection($"Data Source={mbtilesPath};");
            connection.Open();

            var command = connection.CreateCommand();
            command.CommandText = "SELECT tile_data FROM tiles WHERE zoom_level = @z AND tile_column = @x AND tile_row = @y";
            command.Parameters.AddWithValue("@z", z);
            command.Parameters.AddWithValue("@x", x);
            command.Parameters.AddWithValue("@y", FlipY(z, y));  // Flip TMS to XYZ

            var tileData = command.ExecuteScalar() as byte[];

            if (tileData != null)
            {
                return new FileContentResult(tileData, "application/x-protobuf");
            }

            return NoContent();
        }

        private static int FlipY(int zoom, int y) => (1 << zoom) - 1 - y;
    }

}
