using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;

namespace MapsDisplay.Features.LocalAuthority.Controllers
{
    [Route("api/tiles")]
    [ApiController]
    public class TilesController : ControllerBase
    {
        // get local_authorities.mbtiles file directory from Features/Data/Datasets folder 
        // (the file is generated by Tippecanoe [for more info look at INSTRUCTION_TO_GENERATE_MBTILES.MD])
        private readonly string defaultMbtilesPath = Path.Combine(Directory.GetCurrentDirectory(), "Features", "LocalAuthority", "Data", "Datasets", "local_authorities.mbtiles");
        private readonly string _mbtilesPath;
        private readonly ILogger<TilesController> _logger;

        public TilesController(ILogger<TilesController> logger, string? mbtilesPath = null)
        {
            _mbtilesPath = mbtilesPath ?? defaultMbtilesPath;
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        /// <summary>
        /// Retrieves a tile by its zoom level, x, and y coordinates.
        /// </summary>
        /// <param name="z">Zoom level of the tile.</param>
        /// <param name="x">X coordinate of the tile.</param>
        /// <param name="y">Y coordinate of the tile.</param>
        /// <returns>The tile data in protobuf format.</returns>
        [HttpGet("{z:int}/{x:int}/{y:int}.pbf")]
        public IActionResult GetTile(int z, int x, int y)
        {
            // Validate parameters before attempting the query
            if (z < 0 || x < 0 || y < 0)
            {
                _logger.LogWarning("Invalid tile coordinates: z={Z}, x={X}, y={Y}", z, x, y);
                return BadRequest("Tile coordinates cannot be negative.");
            }

            if (!System.IO.File.Exists(_mbtilesPath))
            {
                _logger.LogError("MBTiles file not found at path: {MbtilesPath}", _mbtilesPath);
                return NotFound("MBTiles file not found.");
            }

            try
            {
                SQLitePCL.Batteries_V2.Init();

                using var connection = new SqliteConnection($"Data Source={_mbtilesPath};");
                connection.Open();

                var command = connection.CreateCommand();
                command.CommandText = "SELECT tile_data FROM tiles WHERE zoom_level = @z AND tile_column = @x AND tile_row = @y";
                command.Parameters.AddWithValue("@z", z);
                command.Parameters.AddWithValue("@x", x);
                command.Parameters.AddWithValue("@y", FlipY(z, y));  // Flip TMS to XYZ

                var tileData = command.ExecuteScalar() as byte[];

                if (tileData != null)
                {
                    return new FileContentResult(tileData, "application/x-protobuf");
                }

                return NoContent();
            }
            catch (SqliteException ex)
            {
                _logger.LogError(ex, "Database error occurred while retrieving tile: z={Z}, x={X}, y={Y}", z, x, y);
                return StatusCode(500, "Internal server error while retrieving tile.");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Unexpected error occurred while retrieving tile: z={Z}, x={X}, y={Y}", z, x, y);
                return StatusCode(500, "Unexpected error while retrieving tile.");
            }
        }

        private static int FlipY(int zoom, int y) => (1 << zoom) - 1 - y;
    }

}
